### ISSUE TITLE
Combo characters should only show combo options

### ISSUE THREAD

**Issue by JuanM4T** [agatemosu/kana-test#1]
Tendría más sentido así, porque si no te da la respuesta la mayor parte de las veces. Estaría mejor si solo mostrase combos cuando hay que elegir un combo. 

![image](https://github.com/agatemosu/kana-test/assets/52723130/ad7e646f-65e3-4c37-a467-ab757587923b)
Por ejemplo, en esta imagen, aplicando un poco de lógica, y aún sin saber los caractéres, puedes acertar sin pensar mucho solo viendo que hay una respuesta que es un combo y las demás que no.

**Comment by agatemosu** [comment]
si ya lo sé XD, me di cuenta ya

**Comment by JuanM4T** [comment]
me acabo de dar cuenta que solo genera un combo -o Dakuyon-, el válido, por cada combo -o Dakuyon-, es bastante más importante de lo que creía...
